apiVersion: v1 #version of the API to use
kind: Service #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: ingress-nginx #Name of the service
spec: #specifications for our object
  type: NodePort #exposes a service on each node’s IP address on a specific port
  ports: #
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001 #port range 30000-32767
    protocol: TCP
  selector: #Label selector used to identify pods
    app: nginx